### PR TITLE
Implement/Integrate new design

### LINKED ISSUE #47: Implement/Integrate new design
PoBA should use PoPA style

- [x] Fix get verified bank accounts
- [x] Implement bank accounts list (to verify)
- [x] Implement bank accounts list (verified)
- [x] Add unlock metamask error page
- [x] Add no deploy contract error page
- [x] Add `loadings`
- [x] Add back button
- [x] Improve HelpPage css
- [x] Improve IndexPage css
- [x] Extract common styles and remove dupplicated code in UI components

### PR DESCRIPTION
**Pull request by matiasgaratortiz**
Closes #47

### CODE REVIEW

**Comment by phahulin** [comment]
Could you attach screenshots please?

**Comment by unjapones** [comment]
@phahulin here are a couple of screens:
howitworks
landing
mybankaccounts
okoconfirmed
verify_accounts

**Comment by pashagonchar** [comment]
report
Hi guys, I'm designer from POA Network as you know. When you have questions about design you can ask me, or send me your drafts for report or something else with design.

**Comment by unjapones** [comment]
@phahulin , @pashagonchar fixed some details. Here are the updated screens:

bankaccountstoverify
error
howitworks
landing
verifiedbankaccounts

### Notes

* The "Remove" button from the "verified accounts list" is not displayed because the feature is not implemented yet.
* Responsiveness is not implemented: we can probably create an issue to do it based on how it works on `poa-popa` (I believe this was the DApp that had it implemented, but I may be wrong).
* I would like to simplify a little bit more the UI components we have: end up with less JS files + use CSS or SCSS (probably get rid of `glamorous`), but will leave that for a future ticket.

**Comment by pashagonchar** [comment]
@unjapones I think it's looks ok

**Comment by unjapones** [comment]
@pashagonchar cool! May I ask you to set the approval/review of the PR so we can proceed to merge it?

cc'ing also @phahulin , since he is the other assigned reviewer .

**Comment by pashagonchar** [comment]
@unjapones screens what you attached are ok. Approved.

**Pull request merged**
